<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = date("Y-m-d H:i:s");
        
        $countries = [
            ['name' => 'Afganistán', 'iso_code' => 'AF', 'flag' => '🇦🇫', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Albania', 'iso_code' => 'AL', 'flag' => '🇦🇱', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Alemania', 'iso_code' => 'DE', 'flag' => '🇩🇪', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Andorra', 'iso_code' => 'AD', 'flag' => '🇦🇩', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Angola', 'iso_code' => 'AO', 'flag' => '🇦🇴', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Antigua y Barbuda', 'iso_code' => 'AG', 'flag' => '🇦🇬', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Arabia Saudita', 'iso_code' => 'SA', 'flag' => '🇸🇦', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Argelia', 'iso_code' => 'DZ', 'flag' => '🇩🇿', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Argentina', 'iso_code' => 'AR', 'flag' => '🇦🇷', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Armenia', 'iso_code' => 'AM', 'flag' => '🇦🇲', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Australia', 'iso_code' => 'AU', 'flag' => '🇦🇺', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Austria', 'iso_code' => 'AT', 'flag' => '🇦🇹', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Azerbaiyán', 'iso_code' => 'AZ', 'flag' => '🇦🇿', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Bahamas', 'iso_code' => 'BS', 'flag' => '🇧🇸', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Bangladesh', 'iso_code' => 'BD', 'flag' => '🇧🇩', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Barbados', 'iso_code' => 'BB', 'flag' => '🇧🇧', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Baréin', 'iso_code' => 'BH', 'flag' => '🇧🇭', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Bélgica', 'iso_code' => 'BE', 'flag' => '🇧🇪', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Belice', 'iso_code' => 'BZ', 'flag' => '🇧🇿', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Benín', 'iso_code' => 'BJ', 'flag' => '🇧🇯', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Bielorrusia', 'iso_code' => 'BY', 'flag' => '🇧🇾', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Birmania', 'iso_code' => 'MM', 'flag' => '🇲🇲', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Bolivia', 'iso_code' => 'BO', 'flag' => '🇧🇴', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Bosnia y Herzegovina', 'iso_code' => 'BA', 'flag' => '🇧🇦', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Botsuana', 'iso_code' => 'BW', 'flag' => '🇧🇼', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Brasil', 'iso_code' => 'BR', 'flag' => '🇧🇷', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Brunéi', 'iso_code' => 'BN', 'flag' => '🇧🇳', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Bulgaria', 'iso_code' => 'BG', 'flag' => '🇧🇬', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Burkina Faso', 'iso_code' => 'BF', 'flag' => '🇧🇫', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Burundi', 'iso_code' => 'BI', 'flag' => '🇧🇮', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Bután', 'iso_code' => 'BT', 'flag' => '🇧🇹', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Cabo Verde', 'iso_code' => 'CV', 'flag' => '🇨🇻', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Camboya', 'iso_code' => 'KH', 'flag' => '🇰🇭', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Camerún', 'iso_code' => 'CM', 'flag' => '🇨🇲', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Canadá', 'iso_code' => 'CA', 'flag' => '🇨🇦', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Catar', 'iso_code' => 'QA', 'flag' => '🇶🇦', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Chad', 'iso_code' => 'TD', 'flag' => '🇹🇩', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Chile', 'iso_code' => 'CL', 'flag' => '🇨🇱', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'China', 'iso_code' => 'CN', 'flag' => '🇨🇳', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Chipre', 'iso_code' => 'CY', 'flag' => '🇨🇾', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Colombia', 'iso_code' => 'CO', 'flag' => '🇨🇴', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Comoras', 'iso_code' => 'KM', 'flag' => '🇰🇲', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Congo', 'iso_code' => 'CG', 'flag' => '🇨🇬', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Corea del Norte', 'iso_code' => 'KP', 'flag' => '🇰🇵', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Corea del Sur', 'iso_code' => 'KR', 'flag' => '🇰🇷', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Costa de Marfil', 'iso_code' => 'CI', 'flag' => '🇨🇮', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Costa Rica', 'iso_code' => 'CR', 'flag' => '🇨🇷', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Croacia', 'iso_code' => 'HR', 'flag' => '🇭🇷', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Cuba', 'iso_code' => 'CU', 'flag' => '🇨🇺', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Dinamarca', 'iso_code' => 'DK', 'flag' => '🇩🇰', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Dominica', 'iso_code' => 'DM', 'flag' => '🇩🇲', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Ecuador', 'iso_code' => 'EC', 'flag' => '🇪🇨', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Egipto', 'iso_code' => 'EG', 'flag' => '🇪🇬', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'El Salvador', 'iso_code' => 'SV', 'flag' => '🇸🇻', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Emiratos Árabes Unidos', 'iso_code' => 'AE', 'flag' => '🇦🇪', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Eritrea', 'iso_code' => 'ER', 'flag' => '🇪🇷', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Eslovaquia', 'iso_code' => 'SK', 'flag' => '🇸🇰', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Eslovenia', 'iso_code' => 'SI', 'flag' => '🇸🇮', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'España', 'iso_code' => 'ES', 'flag' => '🇪🇸', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Estados Unidos', 'iso_code' => 'US', 'flag' => '🇺🇸', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Estonia', 'iso_code' => 'EE', 'flag' => '🇪🇪', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Esuatini', 'iso_code' => 'SZ', 'flag' => '🇸🇿', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Etiopía', 'iso_code' => 'ET', 'flag' => '🇪🇹', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Filipinas', 'iso_code' => 'PH', 'flag' => '🇵🇭', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Finlandia', 'iso_code' => 'FI', 'flag' => '🇫🇮', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Fiyi', 'iso_code' => 'FJ', 'flag' => '🇫🇯', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Francia', 'iso_code' => 'FR', 'flag' => '🇫🇷', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Gabón', 'iso_code' => 'GA', 'flag' => '🇬🇦', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Gambia', 'iso_code' => 'GM', 'flag' => '🇬🇲', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Georgia', 'iso_code' => 'GE', 'flag' => '🇬🇪', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Ghana', 'iso_code' => 'GH', 'flag' => '🇬🇭', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Granada', 'iso_code' => 'GD', 'flag' => '🇬🇩', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Grecia', 'iso_code' => 'GR', 'flag' => '🇬🇷', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Guatemala', 'iso_code' => 'GT', 'flag' => '🇬🇹', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Guyana', 'iso_code' => 'GY', 'flag' => '🇬🇾', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Guinea', 'iso_code' => 'GN', 'flag' => '🇬🇳', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Guinea-Bisáu', 'iso_code' => 'GW', 'flag' => '🇬🇼', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Guinea Ecuatorial', 'iso_code' => 'GQ', 'flag' => '🇬🇶', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Haití', 'iso_code' => 'HT', 'flag' => '🇭🇹', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Honduras', 'iso_code' => 'HN', 'flag' => '🇭🇳', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Hungría', 'iso_code' => 'HU', 'flag' => '🇭🇺', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'India', 'iso_code' => 'IN', 'flag' => '🇮🇳', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Indonesia', 'iso_code' => 'ID', 'flag' => '🇮🇩', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Irak', 'iso_code' => 'IQ', 'flag' => '🇮🇶', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Irán', 'iso_code' => 'IR', 'flag' => '🇮🇷', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Irlanda', 'iso_code' => 'IE', 'flag' => '🇮🇪', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Islandia', 'iso_code' => 'IS', 'flag' => '🇮🇸', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Islas Marshall', 'iso_code' => 'MH', 'flag' => '🇲🇭', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Islas Salomón', 'iso_code' => 'SB', 'flag' => '🇸🇧', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Israel', 'iso_code' => 'IL', 'flag' => '🇮🇱', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Italia', 'iso_code' => 'IT', 'flag' => '🇮🇹', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Jamaica', 'iso_code' => 'JM', 'flag' => '🇯🇲', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Japón', 'iso_code' => 'JP', 'flag' => '🇯🇵', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Jordania', 'iso_code' => 'JO', 'flag' => '🇯🇴', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Kazajistán', 'iso_code' => 'KZ', 'flag' => '🇰🇿', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Kenia', 'iso_code' => 'KE', 'flag' => '🇰🇪', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Kirguistán', 'iso_code' => 'KG', 'flag' => '🇰🇬', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Kiribati', 'iso_code' => 'KI', 'flag' => '🇰🇮', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Kuwait', 'iso_code' => 'KW', 'flag' => '🇰🇼', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Laos', 'iso_code' => 'LA', 'flag' => '🇱🇦', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Lesoto', 'iso_code' => 'LS', 'flag' => '🇱🇸', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Letonia', 'iso_code' => 'LV', 'flag' => '🇱🇻', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Líbano', 'iso_code' => 'LB', 'flag' => '🇱🇧', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Liberia', 'iso_code' => 'LR', 'flag' => '🇱🇷', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Libia', 'iso_code' => 'LY', 'flag' => '🇱🇾', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Liechtenstein', 'iso_code' => 'LI', 'flag' => '🇱🇮', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Lituania', 'iso_code' => 'LT', 'flag' => '🇱🇹', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Luxemburgo', 'iso_code' => 'LU', 'flag' => '🇱🇺', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Macedonia del Norte', 'iso_code' => 'MK', 'flag' => '🇲🇰', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Madagascar', 'iso_code' => 'MG', 'flag' => '🇲🇬', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Malasia', 'iso_code' => 'MY', 'flag' => '🇲🇾', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Malaui', 'iso_code' => 'MW', 'flag' => '🇲🇼', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Maldivas', 'iso_code' => 'MV', 'flag' => '🇲🇻', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Malí', 'iso_code' => 'ML', 'flag' => '🇲🇱', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Malta', 'iso_code' => 'MT', 'flag' => '🇲🇹', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Marruecos', 'iso_code' => 'MA', 'flag' => '🇲🇦', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Mauricio', 'iso_code' => 'MU', 'flag' => '🇲🇺', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Mauritania', 'iso_code' => 'MR', 'flag' => '🇲🇷', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'México', 'iso_code' => 'MX', 'flag' => '🇲🇽', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Micronesia', 'iso_code' => 'FM', 'flag' => '🇫🇲', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Moldavia', 'iso_code' => 'MD', 'flag' => '🇲🇩', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Mónaco', 'iso_code' => 'MC', 'flag' => '🇲🇨', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Mongolia', 'iso_code' => 'MN', 'flag' => '🇲🇳', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Montenegro', 'iso_code' => 'ME', 'flag' => '🇲🇪', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Mozambique', 'iso_code' => 'MZ', 'flag' => '🇲🇿', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Namibia', 'iso_code' => 'NA', 'flag' => '🇳🇦', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Nauru', 'iso_code' => 'NR', 'flag' => '🇳🇷', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Nepal', 'iso_code' => 'NP', 'flag' => '🇳🇵', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Nicaragua', 'iso_code' => 'NI', 'flag' => '🇳🇮', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Níger', 'iso_code' => 'NE', 'flag' => '🇳🇪', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Nigeria', 'iso_code' => 'NG', 'flag' => '🇳🇬', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Noruega', 'iso_code' => 'NO', 'flag' => '🇳🇴', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Nueva Zelanda', 'iso_code' => 'NZ', 'flag' => '🇳🇿', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Omán', 'iso_code' => 'OM', 'flag' => '🇴🇲', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Países Bajos', 'iso_code' => 'NL', 'flag' => '🇳🇱', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Pakistán', 'iso_code' => 'PK', 'flag' => '🇵🇰', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Palaos', 'iso_code' => 'PW', 'flag' => '🇵🇼', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Palestina', 'iso_code' => 'PS', 'flag' => '🇵🇸', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Panamá', 'iso_code' => 'PA', 'flag' => '🇵🇦', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Papúa Nueva Guinea', 'iso_code' => 'PG', 'flag' => '🇵🇬', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Paraguay', 'iso_code' => 'PY', 'flag' => '🇵🇾', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Perú', 'iso_code' => 'PE', 'flag' => '🇵🇪', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Polonia', 'iso_code' => 'PL', 'flag' => '🇵🇱', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Portugal', 'iso_code' => 'PT', 'flag' => '🇵🇹', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Reino Unido', 'iso_code' => 'GB', 'flag' => '🇬🇧', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'República Centroafricana', 'iso_code' => 'CF', 'flag' => '🇨🇫', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'República Checa', 'iso_code' => 'CZ', 'flag' => '🇨🇿', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'República del Congo', 'iso_code' => 'CG', 'flag' => '🇨🇬', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'República Democrática del Congo', 'iso_code' => 'CD', 'flag' => '🇨🇩', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'República Dominicana', 'iso_code' => 'DO', 'flag' => '🇩🇴', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Ruanda', 'iso_code' => 'RW', 'flag' => '🇷🇼', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Rumanía', 'iso_code' => 'RO', 'flag' => '🇷🇴', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Rusia', 'iso_code' => 'RU', 'flag' => '🇷🇺', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Samoa', 'iso_code' => 'WS', 'flag' => '🇼🇸', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'San Cristóbal y Nieves', 'iso_code' => 'KN', 'flag' => '🇰🇳', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'San Marino', 'iso_code' => 'SM', 'flag' => '🇸🇲', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'San Vicente y las Granadinas', 'iso_code' => 'VC', 'flag' => '🇻🇨', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Santa Lucía', 'iso_code' => 'LC', 'flag' => '🇱🇨', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Santo Tomé y Príncipe', 'iso_code' => 'ST', 'flag' => '🇸🇹', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Senegal', 'iso_code' => 'SN', 'flag' => '🇸🇳', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Serbia', 'iso_code' => 'RS', 'flag' => '🇷🇸', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Seychelles', 'iso_code' => 'SC', 'flag' => '🇸🇨', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Sierra Leona', 'iso_code' => 'SL', 'flag' => '🇸🇱', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Singapur', 'iso_code' => 'SG', 'flag' => '🇸🇬', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Siria', 'iso_code' => 'SY', 'flag' => '🇸🇾', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Somalia', 'iso_code' => 'SO', 'flag' => '🇸🇴', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Sri Lanka', 'iso_code' => 'LK', 'flag' => '🇱🇰', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Sudáfrica', 'iso_code' => 'ZA', 'flag' => '🇿🇦', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Sudán', 'iso_code' => 'SD', 'flag' => '🇸🇩', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Sudán del Sur', 'iso_code' => 'SS', 'flag' => '🇸🇸', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Suecia', 'iso_code' => 'SE', 'flag' => '🇸🇪', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Suiza', 'iso_code' => 'CH', 'flag' => '🇨🇭', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Surinam', 'iso_code' => 'SR', 'flag' => '🇸🇷', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Tailandia', 'iso_code' => 'TH', 'flag' => '🇹🇭', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Tanzania', 'iso_code' => 'TZ', 'flag' => '🇹🇿', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Tayikistán', 'iso_code' => 'TJ', 'flag' => '🇹🇯', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Timor Oriental', 'iso_code' => 'TL', 'flag' => '🇹🇱', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Togo', 'iso_code' => 'TG', 'flag' => '🇹🇬', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Tonga', 'iso_code' => 'TO', 'flag' => '🇹🇴', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Trinidad y Tobago', 'iso_code' => 'TT', 'flag' => '🇹🇹', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Túnez', 'iso_code' => 'TN', 'flag' => '🇹🇳', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Turkmenistán', 'iso_code' => 'TM', 'flag' => '🇹🇲', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Turquía', 'iso_code' => 'TR', 'flag' => '🇹🇷', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Tuvalu', 'iso_code' => 'TV', 'flag' => '🇹🇻', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Ucrania', 'iso_code' => 'UA', 'flag' => '🇺🇦', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Uganda', 'iso_code' => 'UG', 'flag' => '🇺🇬', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Uruguay', 'iso_code' => 'UY', 'flag' => '🇺🇾', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Uzbekistán', 'iso_code' => 'UZ', 'flag' => '🇺🇿', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Vanuatu', 'iso_code' => 'VU', 'flag' => '🇻🇺', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Vaticano', 'iso_code' => 'VA', 'flag' => '🇻🇦', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Venezuela', 'iso_code' => 'VE', 'flag' => '🇻🇪', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Vietnam', 'iso_code' => 'VN', 'flag' => '🇻🇳', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Yemen', 'iso_code' => 'YE', 'flag' => '🇾🇪', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Yibuti', 'iso_code' => 'DJ', 'flag' => '🇩🇯', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Zambia', 'iso_code' => 'ZM', 'flag' => '🇿🇲', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Zimbabue', 'iso_code' => 'ZW', 'flag' => '🇿🇼', 'created_at' => $now, 'updated_at' => $now],
        ];

        DB::table('countries')->insert($countries);  
    }

}
